/* Generated by tools/gen_hal_stubs.py from aos_hal.h - do not edit.
 *
 * Weak "not available" defaults for every HAL function. The board's
 * aos_hal_p4.c and the simulator's hal_sim.c override them one by one as
 * each block is written (PLAN.md phase 3). */
#include "aos_hal.h"
#include <string.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wunused-parameter"

__attribute__((weak)) int aos_hal_screen_h(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_display_set_rotation(int degrees)
{ }

__attribute__((weak)) int aos_hal_display_get_rotation(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_flush_count(uint64_t *px, uint32_t *frames)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) uint32_t aos_hal_display_flips(void)
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_bench(int frames, aos_display_bench_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_save(char *path_out, size_t n)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_tune_reset(void)
{ }

__attribute__((weak)) void aos_hal_boot_stage(const char *stage)
{ }

__attribute__((weak)) void aos_hal_alive(void)
{ }

__attribute__((weak)) uint32_t aos_hal_caps(void)
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_battery_read(aos_battery_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_imu_read(aos_imu_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) aos_orientation_t aos_hal_imu_orientation(void)
{ aos_orientation_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) uint32_t aos_hal_imu_steps(void)
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_imu_steps_reset(void)
{ }

__attribute__((weak)) void aos_hal_time_now(struct tm *out)
{ }

__attribute__((weak)) bool aos_hal_time_set(const struct tm *t)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_time_is_valid(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_timezone_set(const char *tz)
{ }

__attribute__((weak)) const char * aos_hal_timezone_get(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_rtc_alarm_set(const struct tm *when)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_rtc_alarm_clear(void)
{ }

__attribute__((weak)) int aos_hal_brightness_get(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_brightness_set(int percent)
{ }

__attribute__((weak)) aos_touch_gesture_t aos_hal_touch_gesture(void)
{ aos_touch_gesture_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_touch_frame(aos_touch_frame_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) uint32_t aos_hal_touch_frames(uint32_t after_seq, aos_touch_frame_t *out, uint32_t max)
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_touch_stats(uint32_t *reads, uint32_t *samples)
{ }

__attribute__((weak)) bool aos_hal_touch_multi(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) uint32_t aos_hal_touch_regs(uint8_t regs[AOS_TOUCH_REGS])
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_touch_reg_read(uint8_t reg, uint8_t *val)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_touch_reg_write(uint8_t reg, uint8_t val)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) aos_display_state_t aos_hal_display_state(void)
{ aos_display_state_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_display_set_state(aos_display_state_t state)
{ }

__attribute__((weak)) void aos_hal_set_display_state_cb(void (*cb)(aos_display_state_t state))
{ }

__attribute__((weak)) void aos_hal_main_wait(void)
{ }

__attribute__((weak)) void aos_hal_aod_enable(bool enable)
{ }

__attribute__((weak)) bool aos_hal_aod_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_aod_brightness_set(int percent)
{ }

__attribute__((weak)) int aos_hal_aod_brightness_get(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_screen_timeouts_set(uint32_t active_s, uint32_t aod_s)
{ }

__attribute__((weak)) void aos_hal_screen_timeouts_get(uint32_t *active_s, uint32_t *aod_s)
{ }

__attribute__((weak)) void aos_hal_raise_wake_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_raise_wake_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_display_on(bool on)
{ }

__attribute__((weak)) bool aos_hal_display_is_on(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_activity(void)
{ }

__attribute__((weak)) void aos_hal_screen_idle_tick(bool keep_awake)
{ }

__attribute__((weak)) void aos_hal_sleep(void)
{ }

__attribute__((weak)) void aos_hal_shutdown(void)
{ }

__attribute__((weak)) void aos_hal_reboot(void)
{ }

__attribute__((weak)) void aos_hal_set_button_cb(void (*cb)(aos_button_t button, aos_button_action_t action))
{ }

__attribute__((weak)) bool aos_hal_button_is_down(aos_button_t button)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_power_info(aos_power_info_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_sys_stats(aos_sys_stats_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_batt_history(uint8_t *pct, uint8_t *flags, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_batt_history_mv(uint16_t *mv, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_minute_history(aos_hist_t which, int16_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_tasks(aos_task_info_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_sys_info(aos_sys_info_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_sd_info(aos_sd_info_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_set_power_event_cb(void (*cb)(aos_power_event_t event, int percent))
{ }

__attribute__((weak)) void aos_hal_power_saving_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_power_saving_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_battery_care_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_battery_care_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_panel_sleep_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_panel_sleep_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_light_sleep_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_light_sleep_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_touch_sleep_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_touch_sleep_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_touch_counters(uint32_t *isr, uint32_t *wakes, bool *chip_sleeping)
{ }

__attribute__((weak)) void aos_hal_night_sleep_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_night_sleep_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_set_night_guard_cb(bool (*cb)(int64_t *wake_by))
{ }

__attribute__((weak)) void aos_hal_sleep_hold(const char *who, bool hold)
{ }

__attribute__((weak)) void aos_hal_night_info(uint32_t *nights, uint32_t *chunks, uint32_t *slept_s, int64_t *last_start, int64_t *last_end, uint8_t *last_wake)
{ }

__attribute__((weak)) int aos_hal_power_json(char *out, size_t len)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_net_test_absent(uint32_t seconds, bool idle)
{ }

__attribute__((weak)) void aos_hal_night_test(uint32_t seconds)
{ }

__attribute__((weak)) void aos_hal_imu_gyro_request(bool on)
{ }

__attribute__((weak)) int aos_hal_pmu_rail_count(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_pmu_rail_get(int idx, const char **name, bool *on, int *mv)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_pmu_rail_find(const char *name)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_pmu_rail_set(int idx, bool on)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_pmu_register_read(int reg)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_pmu_register_write(int reg, int value)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) float aos_hal_pmu_ts_voltage(void)
{ float v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_pm_dump_locks(void)
{ }

__attribute__((weak)) int aos_hal_pm_dump_text(char *out, size_t len)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_panel_hw_reset(void)
{ }

__attribute__((weak)) const char * aos_hal_boot_reason(void)
{ return ""; }

__attribute__((weak)) int aos_hal_probe_devices(char *out, size_t len)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_path_apps(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_path_photos(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_path_music(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_path_recordings(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_path_data(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_path_scans(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_path_sd_root(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_sd_release(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_sd_reclaim(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_sd_mark_mounted(bool mounted)
{ }

__attribute__((weak)) const char * aos_hal_path_lang(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_path_icons(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_path_menu(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_sd_present(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_sd_usage(uint64_t *total_bytes, uint64_t *free_bytes)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void * aos_hal_io_alloc(size_t bytes)
{ return NULL; }

__attribute__((weak)) void aos_hal_io_free(void *p)
{ }

__attribute__((weak)) int aos_hal_dir_scan(const char *path, aos_dir_cb_t cb, void *ctx)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_pref_get_i32(const char *key, int32_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_pref_set_i32(const char *key, int32_t value)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_pref_get_str(const char *key, char *out, size_t out_len)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_pref_set_str(const char *key, const char *value)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_pref_erase(const char *key)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_pref_foreach(aos_hal_pref_visit_t visit, void *ctx)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_beep(int freq_hz, int ms)
{ }

__attribute__((weak)) bool aos_hal_play_file(const char *path)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_audio_stop(void)
{ }

__attribute__((weak)) bool aos_hal_audio_is_playing(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_volume_get(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_volume_set(int percent)
{ }

__attribute__((weak)) int aos_hal_mic_level(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_spk_open(uint32_t sample_rate)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_spk_write(const int16_t *pcm, int n)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_spk_queued(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_spk_is_open(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_spk_close(void)
{ }

__attribute__((weak)) bool aos_hal_mic_open(uint32_t sample_rate)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_mic_close(void)
{ }

__attribute__((weak)) int aos_hal_mic_read(int16_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_mic_available(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_mic_status(aos_mic_status_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_mic_gain_set(int db)
{ }

__attribute__((weak)) int aos_hal_mic_gain_get(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_rec_start(const char *path, uint32_t sample_rate)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_rec_pause(void)
{ }

__attribute__((weak)) void aos_hal_rec_resume(void)
{ }

__attribute__((weak)) bool aos_hal_rec_stop(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_rec_status(aos_rec_status_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_rec_peaks(uint8_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_player_play(const char *path)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_player_pause(void)
{ }

__attribute__((weak)) void aos_hal_player_resume(void)
{ }

__attribute__((weak)) void aos_hal_player_stop(void)
{ }

__attribute__((weak)) bool aos_hal_player_status(aos_player_status_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_player_play_folder(const char *path)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_player_next(void)
{ }

__attribute__((weak)) void aos_hal_player_prev(void)
{ }

__attribute__((weak)) void aos_hal_player_seek(uint32_t ms)
{ }

__attribute__((weak)) void aos_hal_player_set_shuffle(bool on)
{ }

__attribute__((weak)) bool aos_hal_player_info(aos_player_info_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_player_last(char *path, size_t len, uint32_t *position_ms)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_player_resume_last(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_player_mix(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_player_set_mix(bool on)
{ }

__attribute__((weak)) void aos_hal_audio_foreground(const char *app_id)
{ }

__attribute__((weak)) bool aos_hal_player_stats(aos_player_stats_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_radio_play(const aos_radio_station_t *list, int count, int index)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_radio_active(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_radio_status(aos_radio_status_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_media_enable(bool enable)
{ }

__attribute__((weak)) bool aos_hal_media_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) aos_media_link_t aos_hal_media_link(void)
{ aos_media_link_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_media_peer(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_media_player(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_media_info(aos_media_info_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_media_command(aos_media_cmd_t cmd)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_bt_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_bt_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) aos_bt_state_t aos_hal_bt_state(void)
{ aos_bt_state_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_bt_peer(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_bt_bonded(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_bt_phone_battery(int *percent)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_bt_forget(void)
{ }

__attribute__((weak)) void aos_hal_bt_pair_begin(void)
{ }

__attribute__((weak)) uint32_t aos_hal_bt_pair_code(void)
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_bt_pair_confirm(bool accept)
{ }

__attribute__((weak)) void aos_hal_bt_pair_cancel(void)
{ }

__attribute__((weak)) void aos_hal_bt_keyboard_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_bt_keyboard_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_bt_keyboard_host(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_bt_keyboard_ready(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_notif_pop(aos_notif_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_notif_pop_removed(uint32_t *uid)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_notif_count(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_notif_at(int index, aos_notif_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_notif_remove(uint32_t uid)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_notif_clear(void)
{ }

__attribute__((weak)) bool aos_hal_notif_action(uint32_t uid, bool positive)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_notif_action_failed(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_notif_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_notif_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_notif_sound_set(bool on)
{ }

__attribute__((weak)) bool aos_hal_notif_sound(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_notif_calls_always_set(bool on)
{ }

__attribute__((weak)) bool aos_hal_notif_calls_always(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_notif_dnd_schedule_set(bool on, int from_min, int to_min)
{ }

__attribute__((weak)) void aos_hal_notif_dnd_schedule_get(bool *on, int *from_min, int *to_min)
{ }

__attribute__((weak)) bool aos_hal_notif_dnd_active(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_notif_categories_set(uint32_t mask)
{ }

__attribute__((weak)) uint32_t aos_hal_notif_categories(void)
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) aos_net_state_t aos_hal_net_state(void)
{ aos_net_state_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_net_low_latency(bool on)
{ }

__attribute__((weak)) const char * aos_hal_net_ssid(void)
{ return ""; }

__attribute__((weak)) int aos_hal_net_rssi(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_net_ip(void)
{ return ""; }

__attribute__((weak)) void aos_hal_net_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_net_enabled(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_net_retry_info(uint32_t *failures, bool *parked, uint32_t *next_s, uint8_t *reason)
{ }

__attribute__((weak)) bool aos_hal_net_sync_time(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_net_has_credentials(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_net_set_credentials(const char *ssid, const char *pass)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_net_forget(void)
{ }

__attribute__((weak)) bool aos_hal_net_ap_start(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_net_ap_stop(void)
{ }

__attribute__((weak)) bool aos_hal_net_ap_active(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_net_ap_ssid(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_net_ap_pass(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_net_ap_ip(void)
{ return ""; }

__attribute__((weak)) int aos_hal_net_ap_clients(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_net_coprocessor_fw(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_net_test_freeze_link(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_net_coprocessor_image(const char *path, char *version, size_t n)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_net_coprocessor_update(const char *path)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_net_coprocessor_status(aos_c6_update_t *out)
{ }

__attribute__((weak)) aos_ap_pass_mode_t aos_hal_net_ap_pass_mode(void)
{ aos_ap_pass_mode_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_net_ap_default_ssid(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_net_ap_set_config(const char *ssid, const char *pass, aos_ap_pass_mode_t mode)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_net_scan(aos_wifi_ap_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_scan_start(uint32_t flags)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_scan_stop(void)
{ }

__attribute__((weak)) bool aos_hal_scan_status(aos_scan_status_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_http_get(const char *url, int max_bytes)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_http_request(const char *method, const char *url, const char *headers, const char *body, const char *content_type, int max_bytes)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) aos_http_state_t aos_hal_http_state(int id)
{ aos_http_state_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_http_status(int id)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_http_body(int id)
{ return ""; }

__attribute__((weak)) int aos_hal_http_len(int id)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_http_release(int id)
{ }

__attribute__((weak)) bool aos_hal_ota_begin(size_t total_bytes)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ota_write(const void *data, size_t len)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ota_end(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_ota_abort(void)
{ }

__attribute__((weak)) const char * aos_hal_ota_error(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_ota_pending_verify(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_ota_mark_valid(void)
{ }

__attribute__((weak)) const char * aos_hal_ota_running_slot(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_ota_boot_other(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ota_info(aos_ota_info_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_hang_restarts(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_coredump_info(aos_coredump_info_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) size_t aos_hal_coredump_read(size_t off, void *buf, size_t len)
{ size_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_coredump_erase(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) aos_hal_usb_mode_t aos_hal_usb_mode(void)
{ aos_hal_usb_mode_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_mode_set(aos_hal_usb_mode_t mode)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_busy(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_keys_ready(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_key(const char *name)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_usb_type(const char *ascii)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_mouse(int dx, int dy, int wheel)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_click(int button)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_gamepad(int x, int y, int hat, unsigned buttons)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_midi_ready(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_midi_note(int note, int velocity, bool on)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_midi_cc(int control, int value)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_midi_bend(int value)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_card_away(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_key_valid(const char *name)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_connected(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_usb_net_up(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_usb_restore(void)
{ }

__attribute__((weak)) bool aos_hal_usb_mouse_hold(int buttons)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) const char * aos_hal_device_name(void)
{ return ""; }

__attribute__((weak)) bool aos_hal_device_name_valid(const char *name)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_device_name_set(const char *name)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_mdns_add_netif(void *esp_netif)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_mdns_remove_netif(void *esp_netif)
{ }

__attribute__((weak)) uint64_t aos_hal_uptime_ms(void)
{ uint64_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_heap_info(uint32_t *free_internal, uint32_t *free_psram)
{ }

__attribute__((weak)) const char * aos_hal_board_name(void)
{ return ""; }

__attribute__((weak)) const char * aos_hal_firmware_version(void)
{ return ""; }

__attribute__((weak)) void aos_hal_log(const char *tag, const char *fmt, ...)
{ }

__attribute__((weak)) void aos_hal_log_level_set(int level)
{ }

__attribute__((weak)) size_t aos_hal_log_total(void)
{ size_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) size_t aos_hal_log_prev_read(size_t from, char *out, size_t out_len, size_t *next)
{ size_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) size_t aos_hal_log_read(size_t from, char *out, size_t out_len, size_t *next)
{ size_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_init(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_thread_start(const char *name, void (*fn)(void *arg), void *arg, uint32_t stack_bytes, int prio)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_sleep_ms(uint32_t ms)
{ }

__attribute__((weak)) void * aos_hal_mutex_create(void)
{ return NULL; }

__attribute__((weak)) void aos_hal_mutex_lock(void *m)
{ }

__attribute__((weak)) void aos_hal_mutex_unlock(void *m)
{ }

__attribute__((weak)) bool aos_hal_lock(uint32_t timeout_ms)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_lvgl_core(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_unlock(void)
{ }

__attribute__((weak)) bool aos_hal_worker_start(const char *name, aos_worker_fn_t fn, void *arg, uint32_t stack_bytes)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_worker_start_on(const char *name, aos_worker_fn_t fn, void *arg, uint32_t stack_bytes, int core, int prio)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_worker_stop(void)
{ }

__attribute__((weak)) bool aos_hal_worker_running(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_worker_should_stop(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_worker_sleep(uint32_t ms)
{ }

__attribute__((weak)) bool aos_hal_worker_split(void (*fn)(void *arg, int part), void *arg)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_blit(int x, int y, int w, int h, const void *rgb565_be)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_blit_scaled(int x, int y, int w, int h, const void *rgb565, int scale, bool big_endian)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_blit_fit(int x, int y, int dst_w, int dst_h, const void *rgb565, int src_w, int src_h, int stride_px, bool big_endian)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_blit_native(int x, int y, int w, int h, const void *rgb565)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) uint16_t * aos_hal_display_back(void)
{ return NULL; }

__attribute__((weak)) bool aos_hal_display_flip(uint16_t *buf)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_back_age(const uint16_t *fb, uint32_t *flips_since, bool *lvgl_touched)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_blit_into(uint16_t *fb, int x, int y, int w, int h, const void *rgb565)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_blit_into_fit(uint16_t *fb, int x, int y, int dst_w, int dst_h, const void *rgb565, int src_w, int src_h, int stride_px, bool big_endian)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_display_fb(const uint16_t **px, int *w, int *h)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void * aos_hal_retro_alloc(size_t bytes)
{ return NULL; }

__attribute__((weak)) void aos_hal_retro_free(void *p)
{ }

__attribute__((weak)) bool aos_hal_retro_scale(const uint16_t *src, int src_w, int src_h, int in_x, int in_y, int in_w, int in_h, int k, uint16_t *dst, size_t dst_bytes, int dst_stride_px, int dst_h, int out_x, int out_y)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) uint64_t aos_hal_uptime_us(void)
{ uint64_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_tcp_connect(const char *host, int port, int timeout_ms)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_tcp_send(int handle, const void *data, int len, int timeout_ms)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_tcp_recv(int handle, void *buf, int max, int timeout_ms)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_tcp_close(int handle)
{ }

__attribute__((weak)) aos_ws_t * aos_hal_ws_open(const char *url, const char *extra_headers, int timeout_ms)
{ return NULL; }

__attribute__((weak)) int aos_hal_ws_send_text(aos_ws_t *ws, const char *text, int len)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_ws_recv_text(aos_ws_t *ws, const char **out, int timeout_ms)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ws_is_open(aos_ws_t *ws)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_ws_close(aos_ws_t *ws)
{ }

__attribute__((weak)) const char * aos_hal_ws_last_error(void)
{ return ""; }

__attribute__((weak)) uint16_t * aos_hal_image_decode(const char *path, uint32_t offset, uint32_t size, int max_w, int max_h, bool fill, int *out_w, int *out_h, int *src_w, int *src_h)
{ return NULL; }

__attribute__((weak)) void aos_hal_image_free(void *px)
{ }

__attribute__((weak)) void aos_hal_md5_hex(const void *data, size_t len, char out[33])
{ }

__attribute__((weak)) aos_h264_t * aos_hal_h264_open(void)
{ return NULL; }

__attribute__((weak)) int aos_hal_h264_decode(aos_h264_t *dec, const uint8_t *nal, int len, aos_h264_pic_t *pic)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_h264_close(aos_h264_t *dec)
{ }

__attribute__((weak)) aos_jpeg_t * aos_hal_jpeg_open(void)
{ return NULL; }

__attribute__((weak)) const uint16_t * aos_hal_jpeg_decode(aos_jpeg_t *j, const void *data, size_t len, int *w, int *h, int *stride_px)
{ return NULL; }

__attribute__((weak)) void aos_hal_jpeg_close(aos_jpeg_t *j)
{ }

__attribute__((weak)) bool aos_hal_jpeg_save(const char *path, const uint16_t *px, int w, int h, int stride_px, int quality)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_steps_get(aos_steps_info_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_steps_set_goal(uint32_t goal)
{ }

__attribute__((weak)) void aos_hal_steps_reset_today(void)
{ }

__attribute__((weak)) bool aos_hal_link_start(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_stop(void)
{ }

__attribute__((weak)) bool aos_hal_link_running(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_link_send(const uint8_t mac[6], const void *data, size_t len)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_link_recv(aos_link_frame_t *out)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_link_stats(aos_link_stats_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_stats_reset(void)
{ }

__attribute__((weak)) bool aos_hal_link_test(const uint8_t mac[6], uint32_t n, uint32_t gap_ms, bool echo, uint16_t len)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_link_test_running(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_offer(const char *app)
{ }

__attribute__((weak)) int aos_hal_link_neighbours(aos_link_neighbour_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_pair_enable(bool on)
{ }

__attribute__((weak)) bool aos_hal_link_pairing(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_bump(void)
{ }

__attribute__((weak)) bool aos_hal_link_partner(aos_link_partner_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_unpair(void)
{ }

__attribute__((weak)) bool aos_hal_link_send_partner(const void *data, size_t len)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) uint32_t aos_hal_link_pair_events(void)
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_link_send_reliable(const void *data, size_t len)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_link_recv_reliable(aos_link_frame_t *out)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_link_reliable_pending(void)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_link_reliable_lost(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_reliable_reset(void)
{ }

__attribute__((weak)) bool aos_hal_link_bulk_test(uint32_t bytes)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_drop_percent(uint32_t pct)
{ }

__attribute__((weak)) void aos_hal_link_bulk_drain(void)
{ }

__attribute__((weak)) void aos_hal_link_bulk_receiver(bool on)
{ }

__attribute__((weak)) void aos_hal_link_set_partner_test(const uint8_t mac[6])
{ }

__attribute__((weak)) void aos_hal_link_set_channel_info(uint8_t channel)
{ }

__attribute__((weak)) bool aos_hal_link_park(uint8_t channel)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) void aos_hal_link_unpark(void)
{ }

__attribute__((weak)) bool aos_hal_link_parked(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) uint32_t aos_hal_link_rejoin_ms(void)
{ uint32_t v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ftm_supported(void)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ftm_responder(bool on)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ftm_responder_info(uint8_t mac[6], uint8_t *channel)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ftm_measure(const uint8_t mac[6], uint8_t channel, uint8_t frames)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_ftm_result(aos_ftm_result_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_net_scan_ex(aos_wifi_ap_ex_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_net_ap_info(aos_wifi_ap_ex_t *out)
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_net_arp_table(aos_arp_entry_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) bool aos_hal_net_mac(uint8_t mac[6])
{ bool v; memset(&v, 0, sizeof v); return v; }

__attribute__((weak)) int aos_hal_mdns_browse(const char *const *types, int ntypes, uint32_t timeout_ms, aos_mdns_svc_t *out, int max)
{ int v; memset(&v, 0, sizeof v); return v; }
