/* Generated by tools/gen_folder_glyphs.py from Material Design Icons 7.4.47.
 * Do not edit: change SETTINGS there and run it again.
 *
 * Each glyph as a UTF-8 string, for a label whose font is aos_settings_font
 * (24 px). */
#pragma once

#include "lvgl.h"

LV_FONT_DECLARE(aos_settings_font);

#define AOS_SG_WIFI                   "\xF3\xB0\x96\xA9"
#define AOS_SG_BLUETOOTH              "\xF3\xB0\x82\xAF"
#define AOS_SG_FLASHLIGHT             "\xF3\xB0\x89\x84"
#define AOS_SG_WATCH_VARIANT          "\xF3\xB0\xA2\x97"
#define AOS_SG_LEAF                   "\xF3\xB0\x8C\xAA"
#define AOS_SG_MOON_WANING_CRESCENT   "\xF3\xB0\xBD\xA5"
#define AOS_SG_USB                    "\xF3\xB0\x95\x93"
#define AOS_SG_BRIGHTNESS_6           "\xF3\xB0\x83\x9F"
#define AOS_SG_VOLUME_HIGH            "\xF3\xB0\x95\xBE"
#define AOS_SG_BELL_OUTLINE           "\xF3\xB0\x82\x9C"
#define AOS_SG_VIEW_GRID_OUTLINE      "\xF3\xB1\x87\x99"
#define AOS_SG_CLOCK_OUTLINE          "\xF3\xB0\x85\x90"
#define AOS_SG_TRANSLATE              "\xF3\xB0\x97\x8A"
#define AOS_SG_BATTERY_HEART_VARIANT  "\xF3\xB1\x88\x91"
#define AOS_SG_GESTURE_TAP            "\xF3\xB0\x9D\x81"
#define AOS_SG_INFORMATION_OUTLINE    "\xF3\xB0\x8B\xBD"
#define AOS_SG_CHART_BOX_OUTLINE      "\xF3\xB1\x95\x8E"
#define AOS_SG_WHITE_BALANCE_SUNNY    "\xF3\xB0\x96\xA8"
#define AOS_SG_CHEVRON_RIGHT          "\xF3\xB0\x85\x82"
#define AOS_SG_CHEVRON_LEFT           "\xF3\xB0\x85\x81"
#define AOS_SG_RESTART                "\xF3\xB0\x9C\x89"
#define AOS_SG_CELLPHONE              "\xF3\xB0\x84\x9C"
#define AOS_SG_LIGHTNING_BOLT         "\xF3\xB1\x90\x8B"
#define AOS_SG_SKIP_PREVIOUS          "\xF3\xB0\x92\xAE"
#define AOS_SG_PLAY                   "\xF3\xB0\x90\x8A"
#define AOS_SG_PAUSE                  "\xF3\xB0\x8F\xA4"
#define AOS_SG_SKIP_NEXT              "\xF3\xB0\x92\xAD"
#define AOS_SG_COG                    "\xF3\xB0\x92\x93"
#define AOS_SG_MUSIC_NOTE             "\xF3\xB0\x8E\x87"
