/*
 * P4OS font set - generated by tools/gen_fonts.py, do not edit.
 *
 * Inter Medium (and SemiBold for icon labels) with Latin-1, so accented text
 * renders. LVGL's own lv_font_montserrat_* are ASCII only and stay
 * compiled in for the dynamic apps that reference them directly.
 *
 * Do not name these fonts in UI code. Go through the role pointers
 * in aos_theme.h (aos_font_huge / title / body / small) so that a
 * language switch can repoint them in one place.
 */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(aos_inter_14);
LV_FONT_DECLARE(aos_inter_16);
LV_FONT_DECLARE(aos_inter_20);
LV_FONT_DECLARE(aos_inter_24);
LV_FONT_DECLARE(aos_inter_28);
LV_FONT_DECLARE(aos_inter_32);
LV_FONT_DECLARE(aos_inter_36);
LV_FONT_DECLARE(aos_inter_48);
LV_FONT_DECLARE(aos_inter_64);
LV_FONT_DECLARE(aos_inter_sb_20);
LV_FONT_DECLARE(aos_inter_num_96);
LV_FONT_DECLARE(aos_inter_num_144);

/* The names AmoledOS code uses. */
#define aos_montserrat_14 aos_inter_14
#define aos_montserrat_16 aos_inter_16
#define aos_montserrat_20 aos_inter_20
#define aos_montserrat_24 aos_inter_24
#define aos_montserrat_28 aos_inter_28
#define aos_montserrat_32 aos_inter_32
#define aos_montserrat_36 aos_inter_36
#define aos_montserrat_48 aos_inter_48
#define aos_montserrat_64 aos_inter_64

#ifdef __cplusplus
}
#endif
