TITLES = {
 'living': [('Primer ovillo','First yarn','Das erste Knäuel'),('Dos ovillos','Two balls of yarn','Zwei Knäuel'),
            ('Detrás del sillón','Behind the armchair','Hinter dem Sessel'),('Hora de la siesta','Nap time','Mittagsschlaf'),
            ('Entre libros','Among books','Zwischen Büchern'),('La alfombra','The rug','Der Teppich'),
            ('Enredos','Tangles','Verheddert'),('El gran ovillo','The great tangle','Das große Durcheinander')],
 'kitchen': [('Un charco','A puddle','Eine Pfütze'),('Piso resbaloso','Slippery floor','Rutschiger Boden'),
             ('Galletitas','Cookies','Kekse'),('La heladera','The fridge','Der Kühlschrank'),
             ('Merienda','Snack time','Kaffeezeit'),('Patinando','Skating','Schlittern'),
             ('La pileta','The sink','Die Spüle'),('Gran limpieza','Big clean-up','Großputz')],
 'garden': [('La placa','The plate','Die Platte'),('La reja','The gate','Das Tor'),
            ('Macetas','Flower pots','Blumentöpfe'),('Después de la lluvia','After the rain','Nach dem Regen'),
            ('Dos placas','Two plates','Zwei Platten'),('El enanito','The gnome','Der Gartenzwerg'),
            ('Laberinto verde','Green maze','Grünes Labyrinth'),('Jardín secreto','Secret garden','Geheimer Garten')],
 'attic': [('La gatera','The cat flap','Die Katzenklappe'),('Cajas y más cajas','Boxes and boxes','Kisten über Kisten'),
           ('Baúles','Trunks','Truhen'),('Dos gateras','Two flaps','Zwei Klappen'),
           ('El caballito','The rocking horse','Das Schaukelpferd'),('Recuerdos','Keepsakes','Andenken'),
           ('La lámpara vieja','The old lamp','Die alte Lampe'),('Todo el altillo','The whole attic','Der ganze Dachboden')],
 'roofs': [('Un hueco','A gap','Eine Lücke'),('Puentes de cajón','Crate bridges','Kistenbrücken'),
           ('La pelota','The ball','Der Ball'),('Rodando','Rolling','Rollen'),
           ('Chimeneas','Chimneys','Schornsteine'),('Noche de lluvia','Rainy night','Regennacht'),
           ('Luna llena','Full moon','Vollmond'),('Sobre la ciudad','Over the town','Über der Stadt')],
}
