#!/usr/bin/env python3
"""Draws Chatarra's 2x world art and writes it as C (ASSETS.md).

    python3 tools/arte2x.py                 # writes main/ch_world2x.inc
    python3 tools/arte2x.py --hoja out.png  # and a contact sheet: 1x | 2x

The drawings live in arte2x_*.py, one function per asset, named after the 1x
array in ch_world.c they replace (PX_PASTO -> HD_PX_PASTO). The output is
plain ASCII maps a person can read and edit; if one is edited by hand, take
it out of the script so the next run does not draw over the edit.
"""
import os, sys, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import arte2x_suelos
import arte2x_cosas
from hoja import paleta, sprites, pintar
from PIL import Image, ImageDraw

AQUI = os.path.dirname(os.path.abspath(__file__))
MAIN = os.path.join(AQUI, '..', 'main')

def todos():
    d = {}
    d.update(arte2x_suelos.SUELOS)
    d.update(arte2x_cosas.COSAS)
    return d

def escribir(dibujos, pal):
    uno = dict(sprites(os.path.join(MAIN, 'ch_world.c')))
    out = ['/* GENERATED by tools/arte2x.py - the 2x art of ch_world.c (ASSETS.md).',
           ' * One array per 1x array it replaces, named HD_<name>, twice as wide',
           ' * and twice as tall. Do not edit here: edit the drawing in the script,',
           ' * or take the asset out of the script before editing it by hand. */', '']
    for nombre, f in dibujos.items():
        L = f()
        filas = L.filas()
        if nombre in uno:
            w1, h1 = max(len(r) for r in uno[nombre]), len(uno[nombre])
            assert (L.w, L.h) == (w1 * 2, h1 * 2), (nombre, L.w, L.h, w1, h1)
        for r in filas:
            for c in r:
                assert c == '.' or c in pal, (nombre, c)
        out.append('static const char *const HD_%s[%d] = {' % (nombre, len(filas)))
        for r in filas:
            # '?' is a colour (snow's shadow), and '??' followed by certain
            # characters is a C trigraph: every '?' is written as the escape
            # \? so no compiler, in any mode, can read one
            out.append('    "%s",' % r.replace('\\', '\\\\').replace('"', '\\"').replace('?', '\\?'))
        out.append('};')
        out.append('')
    open(os.path.join(MAIN, 'ch_world2x.inc'), 'w').write('\n'.join(out))
    # and the lookup from each 1x array to its 2x one, which has to come
    # after the 1x arrays: it is included at the end of ch_world.c
    t = ['/* GENERATED by tools/arte2x.py: which 1x array each 2x one replaces. */',
         'static const struct { const char *const *uno; const char *const *dos; } HD_TABLA[] = {']
    for nombre in dibujos:
        if nombre in uno:
            t.append('    { %s, HD_%s },' % (nombre, nombre))
    t.append('};')
    open(os.path.join(MAIN, 'ch_world2x_tabla.inc'), 'w').write('\n'.join(t) + '\n')
    return len(dibujos)

def hoja(dibujos, pal, path, z=4, filtro=None):
    uno = dict(sprites(os.path.join(MAIN, 'ch_world.c')))
    pares = []
    for nombre, f in dibujos.items():
        if filtro and not re.search(filtro, nombre): continue
        L = f()
        a = pintar(uno[nombre], pal, z * 2) if nombre in uno else None
        b = pintar(L.filas(), pal, z)
        if nombre.startswith('PX_'):            # the tile repeated 2x2, for the seams
            t = Image.new('RGB', (b.width * 2, b.height * 2))
            for i in range(4): t.paste(b, ((i & 1) * b.width, (i >> 1) * b.height))
            b = t
        pares.append((nombre, a, b))
    ancho = 1500
    x = y = 0; alto = 0; pos = []
    for n, a, b in pares:
        w = (a.width + 4 if a else 0) + b.width
        h = max(a.height if a else 0, b.height)
        if x + w > ancho: x = 0; y += alto + 18; alto = 0
        pos.append((x, y, n, a, b)); x += w + 12; alto = max(alto, h)
    im = Image.new('RGB', (ancho, y + alto + 20), (12, 12, 16))
    d = ImageDraw.Draw(im)
    for x, y, n, a, b in pos:
        d.text((x, y), n, fill=(210, 210, 210))
        if a: im.paste(a, (x, y + 12)); x += a.width + 4
        im.paste(b, (x, y + 12))
    im.save(path)

if __name__ == '__main__':
    pal = paleta()
    dib = todos()
    n = escribir(dib, pal)
    print('wrote %d assets to main/ch_world2x.inc' % n)
    if '--hoja' in sys.argv:
        i = sys.argv.index('--hoja')
        filtro = sys.argv[i + 2] if len(sys.argv) > i + 2 else None
        hoja(dib, pal, sys.argv[i + 1], 3, filtro)
