/*
 * AmoledOS - Dynamic loading of applications.
 *
 * Apps are loaded **on demand**: at startup each .so is only opened far enough
 * to read its descriptor (name, icon, colour) and closed again. The code
 * enters RAM only when the user opens the app, and leaves when they close it.
 *
 * This is not an optimisation, it is the only thing that fits. The apps' .text
 * has to live in executable internal RAM, of which there is about 83 KB; the
 * six apps together add up to 134 KB. One at a time, on the other hand, is
 * plenty: the largest is 43 KB. Measured on the board.
 */
#include "aos_dynapp.h"
#include "aos_app.h"
#include "aos_ui.h"
#include "aos_i18n.h"
#include "aos_hal.h"

#include "esp_log.h"
#include "esp_timer.h"
#include "esp_heap_caps.h"
#include "esp_dlfcn.h"
#include "private/elf_symbol.h"

#include <dirent.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <stdio.h>

static const char *TAG = "aos_dynapp";

/* Where the apps' code runs. On the ESP32-S3 it is internal executable RAM
 * (a reservation, below) unless CONFIG_ELF_LOADER_TEXT_PSRAM_MMU maps PSRAM
 * pages on the instruction bus. On the ESP32-P4 data and instructions share
 * the PSRAM addresses, and the loader runs the code where it put it
 * (CONFIG_ELF_LOADER_LOAD_PSRAM): the P4 has no executable heap at all. */
#if CONFIG_ELF_LOADER_TEXT_PSRAM_MMU || (CONFIG_IDF_TARGET_ESP32P4 && CONFIG_ELF_LOADER_LOAD_PSRAM)
#define AOS_CODE_IN_PSRAM 1
#else
#define AOS_CODE_IN_PSRAM 0
#endif

/* How many microSD apps fit.
 *
 * It was at 16 and there were 17 .so files: the seventeenth was discarded by
 * returning false, WITHOUT A SINGLE LOG LINE, and from the other side it
 * looked like an app that simply did not show up in the menu. It is exactly
 * the same bug that had already happened in the simulator with MAX_SIM_APPS
 * (12 slots, 14 apps), so now it is 32 -like over there- and the limit also
 * SAYS SO when it fills up. Each slot is ~230 bytes of .bss, so they are
 * cheap, and they live in PSRAM anyway.
 *
 * It went from 32 to 48 when a module stopped meaning an app: lua.so declares
 * one app per .lua on the card, so 26 .so files can now be forty-something
 * entries. The ceiling has to be above what a card can hold, because the ones
 * that do not fit are whatever readdir happened to return last.
 *
 * Since v0.5.0 it is whatever the launcher leaves after the built-in apps'
 * reservation: 224 of 256. */
#define MAX_DYNAPPS     (AOS_MAX_APPS - AOS_BUILTIN_RESERVE)

/* The descriptor's strings point into the .so's rodata, which disappears when
 * it is closed: a copy of our own has to be kept. */
typedef struct {
    char  file[64];
    char  id[40];
    char  name[40];
    char  icon[16];

    aos_app_t loaded;       /* real callbacks, valid when handle != NULL */
    void     *handle;
    bool      pending_close;
    bool      in_use;

    /* Which app of the module this slot is. Zero for the 26 .so that bring
     * one app each, which is every one of them but lua.so. It is only used
     * to ask the module for the right descriptor when it is reopened: what
     * the app IS, is its id, and the module decides from there. */
    uint16_t  index;
} dynapp_t;

AOS_BSS_PSRAM static dynapp_t s_apps[MAX_DYNAPPS];
static int      s_count;

/* Table generated by tools/gen_symbols.py from the firmware's libraries. If it
 * has not been generated yet, it stays empty and the apps can only use the
 * libc and ESP-IDF symbols elf_loader already brings. */
extern const struct esp_elfsym aos_symbol_table[];

/* --------------------------------------------------------------------------
 * Where the loader gets its memory
 *
 * The component's esp_elf_malloc() asks for MALLOC_CAP_8BIT for everything
 * that is not code, and that lands in internal RAM. The problem is that
 * dlopen() reads the WHOLE file into memory before allocating the .text, so
 * the .so competes with itself for the single large internal block there is:
 *
 *     g2043:  57 KB of file + 43 KB of .text  against a 69 KB block
 *
 * The data does not need to be inside: it goes to PSRAM and internal RAM is
 * left whole for the code, which does have to be executable. It is intercepted
 * with -Wl,--wrap so as not to have to fork the component.
 * -------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 * Contiguous reservation for the apps' code
 *
 * Measured on the board: after opening and closing several apps the executable
 * heap was left with 54 KB free spread over 34 holes, the largest 32 KB. A
 * 45 KB app does not fit even though the total is there. The general heap
 * fragments because it mixes allocations of every size and lifetime.
 *
 * The way out is to set ONE large block aside at startup -when there is no
 * fragmentation yet- and serve the apps' .text from it. Since one app is open
 * at a time, that block fills and empties whole: it cannot be pulverised.
 *
 * The size has to be enough for the largest app without starving the rest.
 *
 * 2026-09-04: RAISING IT TO 80 KB WAS TRIED AND REVERTED.
 *
 * The reason for raising it turned out to be FALSE: it was believed that g2043
 * no longer fitted, comparing xtensa-esp-elf-size's "text" column (58,936 B)
 * against the 48 KB. But that column adds up the whole read-only segment
 * -.rodata, .dynsym, .dynstr, .rela, .hash-, and the loader allocates as
 * executable ONLY the .text section, which is 46,282 B. It fits, and the
 * fallback warning added in __wrap_esp_elf_malloc() did not fire once while
 * loading the 19 apps. To measure this the tool is
 * `xtensa-esp-elf-objdump -h`, not `size`.
 *
 * What was learned is that raising it is NOT free even when there is internal
 * RAM to spare, because it comes out of the same pool WiFi eats from. And that
 * free executable memory has to be looked at IN STEADY STATE, not eight
 * seconds after booting:
 *
 *     reservation 48 KB -> just booted 96.4 KB free, STEADY STATE 41.3 KB
 *     reservation 80 KB -> just booted 62.8 KB free, STEADY STATE  9.3 KB
 *
 * The extra 32 KB cost exactly 32: the mechanism works. But leaving free
 * executable memory at 9 KB is walking straight into the failure mode that
 * gives no warning.
 *
 * Where there IS room: the .so files are compiled without any -O (see the note
 * in HANDOFF-APPS.md section 5.5). With -Os g2043 drops to 28 KB, so the
 * reservation would go from being 94% full to 57% without touching a line of
 * the apps.
 *
 * If something does not fit in the reservation it falls back to the general
 * heap, which is still there, but NOW IT SAYS SO: a silent fallback is what
 * let the g2043 problem go unnoticed for months.
 * -------------------------------------------------------------------------- */

#define POOL_BYTES      (48 * 1024)
#define POOL_MAX_BLOCK  8               /* simultaneous modules, plenty */

static uint8_t *s_pool;
static struct {
    uint32_t off;
    uint32_t len;
    bool     used;
} s_pool_blk[POOL_MAX_BLOCK];

/* Only a build without CONFIG_ELF_LOADER_TEXT_PSRAM_MMU sets the reservation
 * aside (see aos_dynapp_scan()); with the option s_pool stays NULL and the
 * pool_* functions below answer "not ours". */
#if !AOS_CODE_IN_PSRAM
static void pool_init(void)
{
    if (s_pool) {
        return;
    }
    s_pool = heap_caps_malloc(POOL_BYTES, MALLOC_CAP_EXEC);
    if (!s_pool) {
        ESP_LOGW(TAG, "no contiguous reservation: the general heap is used");
        return;
    }
    ESP_LOGI(TAG, "code reservation: %u KB contiguous at %p",
             (unsigned)(POOL_BYTES / 1024), s_pool);
}
#endif

/* First hole that fits. With few large blocks nothing more is needed. */
static void *pool_alloc(uint32_t n)
{
    if (!s_pool || n > POOL_BYTES) {
        return NULL;
    }
    n = (n + 15u) & ~15u;               /* aligned to 16 */

    uint32_t cursor = 0;
    for (;;) {
        uint32_t fin = POOL_BYTES;
        int      choque = -1;

        /* how far the hole starting at 'cursor' reaches */
        for (int i = 0; i < POOL_MAX_BLOCK; i++) {
            if (s_pool_blk[i].used && s_pool_blk[i].off >= cursor &&
                s_pool_blk[i].off < fin) {
                fin = s_pool_blk[i].off;
                choque = i;
            }
        }
        if (fin - cursor >= n) {
            for (int i = 0; i < POOL_MAX_BLOCK; i++) {
                if (!s_pool_blk[i].used) {
                    s_pool_blk[i].off  = cursor;
                    s_pool_blk[i].len  = n;
                    s_pool_blk[i].used = true;
                    return s_pool + cursor;
                }
            }
            return NULL;                /* no free descriptor */
        }
        if (choque < 0) {
            return NULL;                /* no room left */
        }
        cursor = s_pool_blk[choque].off + s_pool_blk[choque].len;
    }
}

static bool pool_free(void *p)
{
    if (!s_pool || (uint8_t *)p < s_pool || (uint8_t *)p >= s_pool + POOL_BYTES) {
        return false;                   /* not ours */
    }
    uint32_t off = (uint32_t)((uint8_t *)p - s_pool);
    for (int i = 0; i < POOL_MAX_BLOCK; i++) {
        if (s_pool_blk[i].used && s_pool_blk[i].off == off) {
            s_pool_blk[i].used = false;
            return true;
        }
    }
    ESP_LOGE(TAG, "free of %p, which is not in the reservation", p);
    return true;                        /* ours all the same: it does not go to the heap */
}


/* State of the code reservation. Since it exists, the general executable heap
 * no longer reflects what the apps have available: the reservation shows as
 * occupied even when it is empty inside. Without this there is no way to look
 * at it. */
void aos_dynapp_pool_info(uint32_t *libre, uint32_t *mayor, int *usados)
{
    uint32_t ocupado = 0, mejor = 0, cursor = 0;
    int n = 0;

    if (!s_pool) {
        if (libre)  *libre  = 0;
        if (mayor)  *mayor  = 0;
        if (usados) *usados = -1;      /* -1 = there is no reservation */
        return;
    }

    for (int i = 0; i < POOL_MAX_BLOCK; i++) {
        if (s_pool_blk[i].used) {
            ocupado += s_pool_blk[i].len;
            n++;
        }
    }

    /* the largest contiguous hole, walking the reservation in order */
    for (;;) {
        uint32_t fin = POOL_BYTES;
        int choque = -1;
        for (int i = 0; i < POOL_MAX_BLOCK; i++) {
            if (s_pool_blk[i].used && s_pool_blk[i].off >= cursor &&
                s_pool_blk[i].off < fin) {
                fin = s_pool_blk[i].off;
                choque = i;
            }
        }
        if (fin - cursor > mejor) {
            mejor = fin - cursor;
        }
        if (choque < 0) {
            break;
        }
        cursor = s_pool_blk[choque].off + s_pool_blk[choque].len;
    }

    if (libre)  *libre  = POOL_BYTES - ocupado;
    if (mayor)  *mayor  = mejor;
    if (usados) *usados = n;
}

bool aos_dynapp_code_in_psram(void)
{
#if AOS_CODE_IN_PSRAM
    return true;
#else
    return false;
#endif
}

void *__wrap_esp_elf_malloc(uint32_t n, bool exec)
{
#if CONFIG_ELF_LOADER_TEXT_PSRAM_MMU
    /* RAM audit prototype: the code goes to PSRAM, 64 KB-aligned so that the
     * loader maps whole instruction-bus pages at it (esp_elf_esp32s3.c). The
     * internal reservation is not used at all. */
    if (exec) {
        void *p = heap_caps_aligned_alloc(0x10000, n, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
        if (!p) {
            ESP_LOGE(TAG, "%u B of code: no PSRAM block", (unsigned)n);
        }
        return p;
    }
#elif AOS_CODE_IN_PSRAM
    /* ESP32-P4: the code in PSRAM on its own cache lines (128 B, L2), so
     * that writing it back and invalidating it never touches anyone else's
     * data. */
    if (exec) {
        void *p = heap_caps_aligned_alloc(128, (n + 127u) & ~127u, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
        if (!p) {
            ESP_LOGE(TAG, "%u B of code: no PSRAM block", (unsigned)n);
        }
        return p;
    }
#endif
    if (exec) {
        void *p = pool_alloc(n);
        if (p) {
            return p;
        }
        /* Falling back to the general heap is not free: it is going back to
         * the scenario the reservation came to solve, and there a large app
         * fits or does not depending on how the fragmentation turned out. Let
         * it show in the log. */
        ESP_LOGW(TAG, "%u B of code did NOT fit in the reservation: going to the "
                      "general heap (free %u B, largest block %u B). If this "
                      "comes up often, the reservation is too small.",
                 (unsigned)n,
                 (unsigned)heap_caps_get_free_size(MALLOC_CAP_EXEC),
                 (unsigned)heap_caps_get_largest_free_block(MALLOC_CAP_EXEC));
        return heap_caps_malloc(n, MALLOC_CAP_EXEC);
    }
    void *p = heap_caps_malloc(n, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    return p ? p : heap_caps_malloc(n, MALLOC_CAP_8BIT);
}

/* The free has to be intercepted TOO: otherwise the loader would hand free() a
 * pointer that never came out of the heap. */
void __wrap_esp_elf_free(void *ptr)
{
    if (!ptr || pool_free(ptr)) {
        return;
    }
    heap_caps_free(ptr);
}


/* --------------------------------------------------------------------------
 * Symbol lookup
 *
 * Every undefined symbol of a .so is looked up here while it loads, at boot
 * for every module and again each time an app opens. The table has ~2,800
 * entries and was walked with strcmp from the top: a libc symbol like memcpy
 * -which is not in it- cost the whole walk before the loader's own table
 * even got asked. So the first scan sorts an index of pointers into it (in
 * PSRAM, ~11 KB) and the lookup is a binary search, a dozen comparisons.
 * Among duplicate names the first in the table still wins, as before.
 * -------------------------------------------------------------------------- */

static const struct esp_elfsym **s_sym_index;
static int      s_sym_count;
static int64_t  s_resolve_us;
static uint32_t s_resolve_calls;

static int sym_cmp(const void *a, const void *b)
{
    const struct esp_elfsym *x = *(const struct esp_elfsym *const *)a;
    const struct esp_elfsym *y = *(const struct esp_elfsym *const *)b;
    int c = strcmp(x->name, y->name);
    if (c) {
        return c;
    }
    return (x < y) ? -1 : (x > y);      /* the table's order among equals */
}

static void sym_index_build(void)
{
    if (s_sym_index) {
        return;
    }
    int n = 0;
    while (aos_symbol_table[n].name) {
        n++;
    }
    s_sym_index = heap_caps_malloc(sizeof(*s_sym_index) * (size_t)n,
                                   MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (!s_sym_index) {
        return;                         /* the linear walk still works */
    }
    for (int i = 0; i < n; i++) {
        s_sym_index[i] = &aos_symbol_table[i];
    }
    qsort(s_sym_index, (size_t)n, sizeof(*s_sym_index), sym_cmp);
    s_sym_count = n;
}

static uintptr_t lookup_own(const char *name)
{
    if (!s_sym_index) {
        for (const struct esp_elfsym *sym = aos_symbol_table; sym->name; sym++) {
            if (strcmp(sym->name, name) == 0) {
                return (uintptr_t)sym->sym;
            }
        }
        return 0;
    }
    int lo = 0, hi = s_sym_count - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int c = strcmp(s_sym_index[mid]->name, name);
        if (c == 0) {
            while (mid > 0 && strcmp(s_sym_index[mid - 1]->name, name) == 0) {
                mid--;
            }
            return (uintptr_t)s_sym_index[mid]->sym;
        }
        if (c < 0) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return 0;
}

static uintptr_t resolver(const char *name)
{
    int64_t t = esp_timer_get_time();
    uintptr_t addr = lookup_own(name);
    if (!addr) {
        addr = elf_find_sym_default(name);
    }
    s_resolve_us += esp_timer_get_time() - t;
    s_resolve_calls++;
    return addr;
}

static dynapp_t *find_by_id(const char *id)
{
    for (int i = 0; i < s_count; i++) {
        if (s_apps[i].in_use && strcmp(s_apps[i].id, id) == 0) {
            return &s_apps[i];
        }
    }
    return NULL;
}

bool aos_dynapp_is_dynamic(const char *app_id)
{
    return app_id && find_by_id(app_id);
}

/* --------------------------------------------------------------------------
 * Opening and closing the .so
 * -------------------------------------------------------------------------- */

/* Opens the module and returns the aos_app_t its init() builds. */
static bool module_open(const char *filename, uint32_t index,
                        void **out_handle, aos_app_t *out_app)
{
    char relative[160];
    snprintf(relative, sizeof(relative), "/%s/%s", AOS_DYNAPP_RELATIVE, filename);

    /* Size and date of the file: without this there is no way to know whether
     * the SD has the freshly compiled .so or an old one, and every subsequent
     * diagnosis is left hanging. It happens more often than it seems. */
    {
        char full[192];
        snprintf(full, sizeof(full), "%s%s", CONFIG_BSP_SD_MOUNT_POINT, relative);
        struct stat st;
        if (stat(full, &st) == 0) {
            struct tm tm_buf;
            char cuando[24] = "?";
            localtime_r(&st.st_mtime, &tm_buf);
            strftime(cuando, sizeof(cuando), "%Y-%m-%d %H:%M", &tm_buf);
            ESP_LOGI(TAG, "  %s: %u bytes, modified %s",
                     filename, (unsigned)st.st_size, cuando);
        } else {
            ESP_LOGW(TAG, "  %s: could not read the size (%s)", filename, full);
        }
    }

    ESP_LOGI(TAG, "opening %s | executable: free %u B, largest block %u B | "
                  "internal: free %u B, largest block %u B",
             filename,
             (unsigned)heap_caps_get_free_size(MALLOC_CAP_EXEC),
             (unsigned)heap_caps_get_largest_free_block(MALLOC_CAP_EXEC),
             (unsigned)heap_caps_get_free_size(MALLOC_CAP_INTERNAL),
             (unsigned)heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL));

    void *handle = dlopen(relative, RTLD_NOW);
    if (!handle) {
        ESP_LOGE(TAG, "dlopen(%s) failed: %s", relative, dlerror());
        /* The map of the executable heap: it distinguishes "there is no
         * memory" from "there is, but in pieces". With 54 KB free and the
         * largest hole at 36 KB, a 45 KB app does not fit even though the
         * total is there. */
        ESP_LOGW(TAG, "--- blocks of the executable heap ---");
        heap_caps_dump(MALLOC_CAP_EXEC);
        return false;
    }

    /* Espressif's loader only indexes symbols of function type, which is why
     * the entry point is two functions and not a structure (see aos_app.h). */
    uint32_t (*abi_fn)(void)            = dlsym(handle, "aos_app_abi");
    bool     (*init_fn)(aos_app_t *app) = dlsym(handle, "aos_app_init");

    /* Optional, and only lua.so has them today: a module that brings several
     * apps (see aos_app.h). Without them the module has exactly one, which is
     * what every other .so on the card is. */
    bool (*init_at_fn)(aos_app_t *app, uint32_t index) =
        dlsym(handle, "aos_app_init_at");

    if (!abi_fn || !init_fn) {
        ESP_LOGE(TAG, "%s does not export aos_app_abi/aos_app_init", filename);
        dlclose(handle);
        return false;
    }

    uint32_t abi = abi_fn();
    if (abi != AOS_ABI_VERSION) {
        ESP_LOGE(TAG, "%s uses ABI %u and the firmware expects %u: rebuild it",
                 filename, (unsigned)abi, (unsigned)AOS_ABI_VERSION);
        dlclose(handle);
        return false;
    }

    memset(out_app, 0, sizeof(*out_app));
    bool ok = init_at_fn ? init_at_fn(out_app, index) : (index == 0 && init_fn(out_app));
    if (!ok) {
        ESP_LOGE(TAG, "%s failed to initialise app %u", filename, (unsigned)index);
        dlclose(handle);
        return false;
    }

    *out_handle = handle;
    return true;
}


static void module_close(dynapp_t *app);

/* Second attempt when there is no executable memory.
 *
 * Two levels, and deliberately NEITHER evicts an active background app: if the
 * Recorder is recording, unloading it stops the recording without warning.
 * Failing with a message saying who is holding the memory is preferred.
 *
 *   1. Drain the pending closes. dyn_destroy() only marks; the real close
 *      happens on the next aos_dynapp_tick(). If the load is attempted before
 *      that tick, it fails with the memory one step away.
 *   2. Unload modules that were left loaded without being in use or being
 *      background ones. There should not be any; if one turns up, it is a bug
 *      and this papers over it -but leaves it noted in the log-. */
static bool liberar_ejecutable(const dynapp_t *excepto)
{
    bool libero = false;

    for (int i = 0; i < s_count; i++) {
        dynapp_t *a = &s_apps[i];
        if (!a->in_use || &s_apps[i] == excepto || !a->handle) {
            continue;
        }
        if (a->pending_close) {
            ESP_LOGW(TAG, "out of memory: closing %s early", a->file);
            a->pending_close = false;
            module_close(a);
            libero = true;
        }
    }
    return libero;
}

/* Who is holding memory, so we can tell the user. */
static const char *retenedor(void)
{
    for (int i = 0; i < s_count; i++) {
        if (s_apps[i].in_use && s_apps[i].handle) {
            return s_apps[i].name[0] ? s_apps[i].name : s_apps[i].file;
        }
    }
    return NULL;
}

static bool module_ensure_open(dynapp_t *app)
{
    if (app->handle) {
        app->pending_close = false;     /* it was reopened before being closed */
        return true;
    }
    if (module_open(app->file, app->index, &app->handle, &app->loaded)) {
        return true;
    }

    /* One retry, after recovering whatever can be recovered without breaking
     * anything. */
    if (liberar_ejecutable(app) &&
        module_open(app->file, app->index, &app->handle, &app->loaded)) {
        ESP_LOGI(TAG, "%s loaded on the second attempt", app->file);
        return true;
    }
    return false;
}

static void module_close(dynapp_t *app)
{
    if (!app->handle) {
        ESP_LOGW(TAG, "closing %s with no handle: was it already unloaded?", app->file);
        return;
    }
    dlclose(app->handle);
    app->handle = NULL;
    memset(&app->loaded, 0, sizeof(app->loaded));
    ESP_LOGI(TAG, "%s unloaded (executable free: %u B)", app->file,
             (unsigned)heap_caps_get_free_size(MALLOC_CAP_EXEC));
}

/* --------------------------------------------------------------------------
 * Trampolines: what the UI runtime sees
 * -------------------------------------------------------------------------- */

static void *dyn_create(aos_app_t *self, lv_obj_t *root)
{
    /* USB disk mode: the computer has the card, where the .so and its files
     * live (aos_usb_p4.c) */
    if (aos_hal_usb_card_away()) {
        aos_ui_toast(_("La computadora tiene la tarjeta.\nExpulsala ahí para volver a usar las apps."), 3000);
        return NULL;
    }
    dynapp_t *app = find_by_id(self->desc.id);
    if (!app || !module_ensure_open(app)) {
        /* Saying WHO is holding the memory: without that the user has no way
         * of knowing that closing another app solves it. */
        const char *quien = retenedor();
        char aviso[96];
        if (quien) {
            snprintf(aviso, sizeof(aviso),
                     _("Sin memoria.\n%s sigue en segundo plano:\ncerrala para liberar"),
                     quien);
        } else {
            snprintf(aviso, sizeof(aviso), "%s", _("No se pudo cargar la app"));
        }
        aos_ui_toast(aviso, 3000);
        return NULL;
    }
    return app->loaded.create ? app->loaded.create(self, root) : NULL;
}

static void dyn_destroy(aos_app_t *self, void *inst)
{
    dynapp_t *app = find_by_id(self->desc.id);
    if (!app) {
        ESP_LOGE(TAG, "destroy of '%s' but it is not in the table",
                 self->desc.id ? self->desc.id : "(no id)");
        return;
    }
    if (app->loaded.destroy) {
        app->loaded.destroy(self, inst);
    }
    /* The dlclose does NOT go here: the runtime deletes the LVGL objects after
     * this callback, and those objects may have callbacks living inside the
     * .so. It is closed on the next tick, with everything already deleted. */
    app->pending_close = true;
}

static void dyn_show(aos_app_t *self, void *inst)
{
    dynapp_t *app = find_by_id(self->desc.id);
    if (app && app->loaded.show) {
        app->loaded.show(self, inst);
    }
}

static void dyn_hide(aos_app_t *self, void *inst)
{
    dynapp_t *app = find_by_id(self->desc.id);
    if (app && app->loaded.hide) {
        app->loaded.hide(self, inst);
    }
}

static bool dyn_back(aos_app_t *self, void *inst)
{
    dynapp_t *app = find_by_id(self->desc.id);
    return (app && app->loaded.back) ? app->loaded.back(self, inst) : false;
}

static bool dyn_button(aos_app_t *self, void *inst, int action)
{
    dynapp_t *app = find_by_id(self->desc.id);
    return (app && app->loaded.button) ? app->loaded.button(self, inst, action) : false;
}

static void dyn_tick(aos_app_t *self, void *inst)
{
    dynapp_t *app = find_by_id(self->desc.id);
    if (app && app->loaded.tick) {
        app->loaded.tick(self, inst);
    }
}

/* -------------------------------------------------------------------------- */

/* Where a scan's time goes, logged at its end (docs/MENU.md). */
static struct {
    int64_t open_us;        /* dlopen + the probe's init() */
    int64_t lock_us;        /* waiting for the UI's lock */
    int64_t reg_us;         /* aos_ui_register_app itself */
} s_scan_cost;

/* Registers apps of one module, from index 'from' to the end, or only the
 * first when first_only. Returns how many were registered and, in *total,
 * how many the module declares.
 *
 * The UI's lock is taken once per batch and not once per app: at boot the
 * UI task is drawing, and every separate lock is a wait for its frame to
 * end. A module with many apps (lua.so) paid that wait once per script. */
#define REGISTER_BATCH  16

static int register_apps(const char *filename, bool first_only, uint32_t *total)
{
    *total = 0;
    if (s_count >= MAX_DYNAPPS) {
        ESP_LOGE(TAG, "%s does not fit: the limit is %d dynamic apps and there are "
                      "already %d. Raise MAX_DYNAPPS or take a .so off the card",
                 filename, MAX_DYNAPPS, s_count);
        return 0;
    }

    int64_t t = esp_timer_get_time();
    void *handle = NULL;
    aos_app_t probe;
    if (!module_open(filename, 0, &handle, &probe)) {
        return 0;
    }
    s_scan_cost.open_us += esp_timer_get_time() - t;

    /* How many apps this module brings. Only lua.so answers; for everything
     * else the symbol is absent and the answer is one. The module stays open
     * for the whole loop: the alternative is a dlopen per app, and lua.so is
     * 144 KB. */
    uint32_t (*count_fn)(void) = dlsym(handle, "aos_app_count");
    bool (*init_at_fn)(aos_app_t *app, uint32_t index) =
        dlsym(handle, "aos_app_init_at");
    uint32_t n = (count_fn && init_at_fn) ? count_fn() : 1;
    if (n < 1) {
        n = 1;
    }
    *total = n;

    uint32_t from = first_only ? 0 : 1;
    uint32_t to   = first_only ? 1 : n;
    int registered = 0;
    bool locked = false;
    int in_batch = 0;

    for (uint32_t i = from; i < to; i++) {
        if (s_count >= MAX_DYNAPPS) {
            ESP_LOGE(TAG, "%s app %u does not fit: the limit is %d",
                     filename, (unsigned)i, MAX_DYNAPPS);
            break;
        }
        if (i > 0) {
            memset(&probe, 0, sizeof(probe));
            if (!init_at_fn(&probe, i)) {
                ESP_LOGE(TAG, "%s failed to describe app %u", filename, (unsigned)i);
                continue;
            }
        }

        dynapp_t *slot = &s_apps[s_count];
        memset(slot, 0, sizeof(*slot));
        snprintf(slot->file, sizeof(slot->file), "%s", filename);
        snprintf(slot->id,   sizeof(slot->id),   "%s", probe.desc.id   ? probe.desc.id   : filename);
        snprintf(slot->name, sizeof(slot->name), "%s", probe.desc.name ? probe.desc.name : filename);
        snprintf(slot->icon, sizeof(slot->icon), "%s", probe.desc.icon ? probe.desc.icon : "");
        slot->index = (uint16_t)i;

        aos_app_t stub = {0};
        stub.desc = probe.desc;
        stub.desc.id   = slot->id;      /* pointing at OUR copies */
        stub.desc.name = slot->name;
        stub.desc.icon = slot->icon[0] ? slot->icon : NULL;

        stub.create  = dyn_create;
        stub.destroy = dyn_destroy;
        stub.show    = dyn_show;
        stub.hide    = dyn_hide;
        stub.back    = dyn_back;
        stub.button  = dyn_button;
        stub.tick    = dyn_tick;

        slot->in_use = true;
        s_count++;

        if (!locked) {
            t = esp_timer_get_time();
            locked = aos_hal_lock(1000);
            s_scan_cost.lock_us += esp_timer_get_time() - t;
        }
        bool ok = false;
        if (locked) {
            t = esp_timer_get_time();
            ok = aos_ui_register_app(&stub);
            s_scan_cost.reg_us += esp_timer_get_time() - t;
            if (++in_batch >= REGISTER_BATCH) {
                aos_hal_unlock();       /* let a frame through */
                locked = false;
                in_batch = 0;
            }
        }
        if (!ok) {
            /* aos_ui_register_app says why in its own log line; this one
             * names the file, which is what tells you which .so to look at. */
            ESP_LOGE(TAG, "%s[%u] -> %s was refused by the launcher",
                     filename, (unsigned)i, slot->id);
            slot->in_use = false;
            s_count--;
            continue;
        }
        registered++;
        ESP_LOGD(TAG, "registered %s[%u] -> %s (%s)",
                 filename, (unsigned)i, slot->id, slot->name);
    }
    if (locked) {
        aos_hal_unlock();
    }
    if (registered) {
        ESP_LOGI(TAG, "registered %s: %d app%s%s", filename, registered,
                 registered == 1 ? "" : "s", first_only && n > 1 ? " (more later)" : "");
    }

    /* descriptors read, the code goes away: it comes back in when it is opened */
    dlclose(handle);
    return registered;
}

bool aos_dynapp_load(const char *filename)
{
    if (!filename) {
        return false;
    }
    /* One module arriving after boot: all of its apps, in the same two steps
     * as the scan. */
    uint32_t total = 0;
    if (register_apps(filename, true, &total) == 0) {
        return false;
    }
    if (total > 1) {
        register_apps(filename, false, &total);
    }
    return true;
}

bool aos_dynapp_unload(const char *app_id)
{
    dynapp_t *app = find_by_id(app_id);
    if (!app) {
        return false;
    }

    bool ok = false;
    if (aos_hal_lock(1000)) {
        ok = aos_ui_unregister_app(app_id);
        aos_hal_unlock();
    }
    if (ok) {
        module_close(app);
        app->in_use = false;
    }
    return ok;
}


/* Which modules are still loaded and how much executable memory they hold.
 *
 * An app with AOS_APP_FLAG_BACKGROUND is not destroyed on exit, so its .so
 * stays loaded until a restart. That is deliberate (the recorder has to go on
 * recording) but it is paid for in memory: PSRAM and MMU pages now, and until
 * v0.3.3 the internal reservation the code of ALL dynamic apps came from.
 * Without this list there is no way to know who is holding it. */
int aos_dynapp_loaded_list(char *out, size_t len)
{
    int n = 0;
    size_t used = 0;
    if (out && len) {
        out[0] = 0;
    }
    for (int i = 0; i < s_count; i++) {
        if (!s_apps[i].in_use || !s_apps[i].handle) {
            continue;
        }
        n++;
        if (out && used + 2 < len) {
            used += (size_t)snprintf(out + used, len - used, "%s%s",
                                     used ? " " : "", s_apps[i].file);
        }
    }
    return n;
}

void aos_dynapp_tick(void)
{
    for (int i = 0; i < s_count; i++) {
        if (s_apps[i].in_use && s_apps[i].pending_close) {
            s_apps[i].pending_close = false;
            module_close(&s_apps[i]);
        }
    }
}

static bool ends_with_so(const char *name)
{
    size_t len = strlen(name);
    return len > 3 && strcmp(name + len - 3, ".so") == 0;
}

int aos_dynapp_scan(void)
{
    /* Before anything else: the reservation is asked for with the heap still
     * whole. The scan opens and closes each .so, and afterwards WiFi starts,
     * which takes some 35 KB of this same memory. Asking for it later would be
     * asking for it already fragmented, which is precisely what we want to
     * avoid. */
#if !AOS_CODE_IN_PSRAM
    pool_init();
#else
    ESP_LOGI(TAG, "apps' code runs from PSRAM: no internal reservation");
#endif

    int64_t ti = esp_timer_get_time();
    sym_index_build();
    ESP_LOGI(TAG, "symbol index: %d entries, %u ms", s_sym_count,
             (unsigned)((esp_timer_get_time() - ti) / 1000));
    elf_set_symbol_resolver(resolver);

    ESP_LOGI(TAG, "executable memory: %u B free, largest block %u B",
             (unsigned)heap_caps_get_free_size(MALLOC_CAP_EXEC),
             (unsigned)heap_caps_get_largest_free_block(MALLOC_CAP_EXEC));

    DIR *dir = opendir(AOS_DYNAPP_DIR);
    if (!dir) {
        ESP_LOGI(TAG, "there is no %s folder, no dynamic apps", AOS_DYNAPP_DIR);
        return 0;
    }

    /* The loader logs every symbol of every module at INFO: hundreds of lines
     * per .so, which is what made the 16 KB log ring forget the boot before
     * anyone could read it. Its warnings and errors still come through. */
    static const char *const LOUD[] = { "ELF", "DLMOD", "DLFCN", "elf_arch",
                                        "ELF_SYMBOL", "elf_s3mmu" };
    for (size_t i = 0; i < sizeof(LOUD) / sizeof(LOUD[0]); i++) {
        esp_log_level_set(LOUD[i], ESP_LOG_WARN);
    }

    /* Two passes. The first registers ONE app of every module; the second
     * the rest of the modules that declare several (lua.so, one app per
     * script). Before, readdir's order decided: with 200 scripts on the card
     * lua.so came before turbo.so, took the slots, and turbo and monsterhop
     * were the ones left out. A card full of scripts must never push a real
     * app out of the launcher. Timed, since every .so is opened here and this
     * is where a card with many apps costs boot time (docs/MENU.md). */
    memset(&s_scan_cost, 0, sizeof(s_scan_cost));
    s_resolve_us = 0;
    s_resolve_calls = 0;
    int64_t t0 = esp_timer_get_time();
    enum { DEFERRED_MAX = 8 };
    char deferred[DEFERRED_MAX][64];
    int n_deferred = 0;

    int loaded = 0;
    struct dirent *item;
    /* how many there are, for the boot screen's bar */
    int files = 0, seen = 0;
    while ((item = readdir(dir)) != NULL)
        if (item->d_name[0] != '.' && ends_with_so(item->d_name)) files++;
    rewinddir(dir);
    if (aos_hal_lock(1000)) {
        aos_ui_hold_home(true);
        aos_hal_unlock();
    }
    while ((item = readdir(dir)) != NULL) {
        if (item->d_name[0] == '.' || !ends_with_so(item->d_name)) {
            continue;
        }
        if (aos_hal_lock(1000)) {
            aos_ui_boot_progress(seen++, files + 1);
            aos_hal_unlock();
        }
        uint32_t total = 0;
        if (register_apps(item->d_name, true, &total) > 0) {
            loaded++;
            if (total > 1 && n_deferred < DEFERRED_MAX) {
                snprintf(deferred[n_deferred++], sizeof(deferred[0]), "%s", item->d_name);
            }
        }
    }
    closedir(dir);
    int64_t t1 = esp_timer_get_time();

    for (int i = 0; i < n_deferred; i++) {
        uint32_t total = 0;
        register_apps(deferred[i], false, &total);
    }
    /* the home screen once, with every app in it */
    if (aos_hal_lock(2000)) {
        aos_ui_boot_progress(files, files + 1);
        aos_ui_hold_home(false);
        aos_hal_unlock();
    }
    int64_t t2 = esp_timer_get_time();

    ESP_LOGI(TAG, "scan: %d modules, %d apps, %u ms (modules %u ms, extra apps %u ms; "
                  "open %u, of it symbols %u for %u lookups; lock wait %u, register %u)",
             loaded, s_count, (unsigned)((t2 - t0) / 1000),
             (unsigned)((t1 - t0) / 1000), (unsigned)((t2 - t1) / 1000),
             (unsigned)(s_scan_cost.open_us / 1000), (unsigned)(s_resolve_us / 1000),
             (unsigned)s_resolve_calls, (unsigned)(s_scan_cost.lock_us / 1000),
             (unsigned)(s_scan_cost.reg_us / 1000));
    return loaded;
}
