/*
 * Language catalogues that travel inside the binary.
 *
 * The contents are generated by tools/gen_lang.py embed; this only describes
 * the shape. It is a private header of aos_ui: aos_i18n.c uses it and nobody
 * else.
 */
#pragma once

typedef struct {
    const char *file;   /* "_sistema.lang", "demo.2043.lang", ... */
    const char *blob;   /* the whole catalogue, without the "#:" comments */
} aos_lang_file_t;

typedef struct {
    const char *code;   /* "en" */
    const char *name;   /* "English" */
    int         strings;
    int         apps;
    const aos_lang_file_t *files;
    int         nfiles;
} aos_lang_pack_t;

extern const aos_lang_pack_t aos_lang_packs[];
extern const int aos_lang_pack_count;
