#include "aos_theme.h"
#include "aos_fonts.h"
#include "aos_i18n.h"
#include "aos_emoji.h"
#include <string.h>

const lv_font_t *aos_font_huge    = NULL;
const lv_font_t *aos_font_large   = NULL;
const lv_font_t *aos_font_title   = NULL;
const lv_font_t *aos_font_body    = NULL;
const lv_font_t *aos_font_small   = NULL;
const lv_font_t *aos_font_caption = NULL;
const lv_font_t *aos_font_tiny    = NULL;
const lv_font_t *aos_font_label   = &aos_inter_sb_20;

/* Picks the compiled font closest to the requested size.
 *
 * These are the aos_montserrat_* fonts from components/aos_fonts, generated by
 * tools/gen_fonts.py with the Latin-1 supplement. LVGL's own
 * lv_font_montserrat_* are ASCII only: they have no accented vowels at all, so
 * any Spanish text written properly renders with holes. They stay compiled in
 * because four dynamic apps still name them directly, but nothing in the UI
 * should reach for them.
 *
 * The table is no longer conditional. The old #if LV_FONT_MONTSERRAT_* guards
 * existed because the set of built-in sizes differed between the simulator
 * (lv_conf.h) and the board (Kconfig); our own fonts are always all there. */
static const lv_font_t *pick(int want)
{
    const struct { int size; const lv_font_t *font; } table[] = {
        { 64, &aos_inter_64 },
        { 48, &aos_inter_48 },
        { 36, &aos_inter_36 },
        { 32, &aos_inter_32 },
        { 28, &aos_inter_28 },
        { 24, &aos_inter_24 },
        { 20, &aos_inter_20 },
        { 16, &aos_inter_16 },
        { 14, &aos_inter_14 },
        { 0, NULL },
    };

    const lv_font_t *best = LV_FONT_DEFAULT;
    int best_diff = 1000;
    for (int i = 0; table[i].font; i++) {
        int diff = table[i].size > want ? table[i].size - want : want - table[i].size;
        if (diff < best_diff) {
            best_diff = diff;
            best = table[i].font;
        }
    }
    return best;
}

#ifdef AOS_SIM
/* Simulator only: P4_SIM_FONT=<dir> replaces the text roles with LVGL binary
 * fonts from sim_fs/fonts/<dir>/<px>.bin (tools/font_preview.py makes them),
 * to compare typefaces without rebuilding. The compiled Montserrat stays as
 * the fallback, which is where the LV_SYMBOL glyphs live. */
#include <stdio.h>
#include <stdlib.h>
static const lv_font_t *sim_font(int px, const lv_font_t *fallback)
{
    const char *dir = getenv("P4_SIM_FONT");
    if (!dir || !*dir) return fallback;
    char path[160];
    snprintf(path, sizeof path, "A:sim_fs/fonts/%s/%d.bin", dir, px);
    lv_font_t *f = lv_binfont_create(path);
    if (!f) { printf("[font] %s missing\n", path); return fallback; }
    f->fallback = fallback;
    return f;
}
#endif

void aos_theme_init(void)
{
    aos_font_huge    = pick(64);
    aos_font_large   = pick(48);
    aos_font_title   = pick(36);
    aos_font_body    = pick(28);
    aos_font_small   = pick(24);
    aos_font_caption = pick(20);
    aos_font_tiny    = pick(16);
#ifdef AOS_SIM
    aos_font_huge    = sim_font(64, aos_font_huge);
    aos_font_large   = sim_font(48, aos_font_large);
    aos_font_title   = sim_font(36, aos_font_title);
    aos_font_body    = sim_font(28, aos_font_body);
    aos_font_small   = sim_font(24, aos_font_small);
    aos_font_caption = sim_font(20, aos_font_caption);
    aos_font_tiny    = sim_font(16, aos_font_tiny);
#endif
    /* colour emoji when the card has the pack (aos_emoji.c): each role gets
     * a copy of its font that falls back to the emoji of its size */
    if (aos_emoji_init()) {
        aos_font_huge    = aos_emoji_font(aos_font_huge);
        aos_font_large   = aos_emoji_font(aos_font_large);
        aos_font_title   = aos_emoji_font(aos_font_title);
        aos_font_body    = aos_emoji_font(aos_font_body);
        aos_font_small   = aos_emoji_font(aos_font_small);
        aos_font_caption = aos_emoji_font(aos_font_caption);
        aos_font_tiny    = aos_emoji_font(aos_font_tiny);
    }

    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, AOS_C_BG, 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);
    lv_obj_set_style_text_color(scr, AOS_C_TEXT, 0);
    lv_obj_set_style_text_font(scr, aos_font_body, 0);
}

lv_obj_t *aos_page(lv_obj_t *parent)
{
    lv_obj_t *page = lv_obj_create(parent);
    lv_obj_remove_style_all(page);
    lv_obj_set_size(page, lv_pct(100), lv_pct(100));
    lv_obj_set_style_bg_color(page, AOS_C_BG, 0);
    lv_obj_set_style_bg_opa(page, LV_OPA_COVER, 0);
    lv_obj_set_style_text_color(page, AOS_C_TEXT, 0);
    lv_obj_set_style_text_font(page, aos_font_body, 0);
    lv_obj_remove_flag(page, LV_OBJ_FLAG_SCROLLABLE);
    return page;
}

lv_obj_t *aos_label(lv_obj_t *parent, const char *text,
                    const lv_font_t *font, lv_color_t color)
{
    lv_obj_t *label = lv_label_create(parent);
    lv_label_set_text(label, text ? text : "");
    if (font) {
        lv_obj_set_style_text_font(label, font, 0);
    }
    lv_obj_set_style_text_color(label, color, 0);
    return label;
}

lv_obj_t *aos_label_boxed(lv_obj_t *parent, const char *text,
                          const lv_font_t *font, lv_color_t color,
                          int32_t width, int32_t height)
{
    lv_obj_t *label = aos_label(parent, text, font, color);
    lv_obj_set_size(label, width, height);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_pad_all(label, 0, 0);
    return label;
}

lv_obj_t *aos_label_scaled(lv_obj_t *parent, const char *text,
                           const lv_font_t *font, lv_color_t color,
                           int32_t scale)
{
    lv_obj_t *label = aos_label(parent, text, font, color);
    lv_obj_set_style_transform_scale(label, scale, 0);
    lv_obj_set_style_transform_pivot_x(label, lv_pct(50), 0);
    lv_obj_set_style_transform_pivot_y(label, lv_pct(50), 0);
    return label;
}

lv_obj_t *aos_button(lv_obj_t *parent, const char *text, lv_color_t color,
                     lv_event_cb_t cb, void *user_data)
{
    lv_obj_t *btn = lv_button_create(parent);
    lv_obj_set_style_bg_color(btn, color, 0);
    lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(btn, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_shadow_width(btn, 0, 0);
    lv_obj_set_style_border_width(btn, 0, 0);
    lv_obj_set_style_pad_hor(btn, 22, 0);
    lv_obj_set_style_pad_ver(btn, 14, 0);
    /* Touch feedback through background opacity, not through scale: a
     * transform is a LAYER, and every layer that does not fit in memory hangs
     * LVGL in an infinite retry. This draws for free. */
    lv_obj_set_style_bg_opa(btn, LV_OPA_60, LV_STATE_PRESSED);

    if (text) {
        lv_obj_t *label = lv_label_create(btn);
        lv_label_set_text(label, text);
        lv_obj_set_style_text_font(label, aos_font_body, 0);
        lv_obj_center(label);
    }
    if (cb) {
        lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, user_data);
    }
    return btn;
}

lv_obj_t *aos_hand_create(lv_obj_t *parent, int32_t width, int32_t length,
                          lv_color_t color)
{
    lv_obj_t *hand = lv_obj_create(parent);
    lv_obj_remove_style_all(hand);
    lv_obj_remove_flag(hand, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_size(hand, width, length);
    lv_obj_set_style_bg_color(hand, color, 0);
    lv_obj_set_style_bg_opa(hand, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(hand, width / 2, 0);
    /* pivot at the bottom tip; aligning with an offset of -length/2 leaves the
     * rotation centred on the middle of the parent */
    lv_obj_set_style_transform_pivot_x(hand, width / 2, 0);
    lv_obj_set_style_transform_pivot_y(hand, length, 0);
    lv_obj_align(hand, LV_ALIGN_CENTER, 0, -length / 2);
    return hand;
}

void aos_hand_set_angle(lv_obj_t *hand, int32_t deg_tenths)
{
    lv_obj_set_style_transform_rotation(hand, deg_tenths, 0);
}

void aos_make_decorative(lv_obj_t *obj)
{
    if (!obj) {
        return;
    }
    lv_obj_remove_flag(obj, LV_OBJ_FLAG_CLICKABLE);
    uint32_t count = lv_obj_get_child_count(obj);
    for (uint32_t i = 0; i < count; i++) {
        aos_make_decorative(lv_obj_get_child(obj, i));
    }
}

const char *aos_day_name(int wday)
{
    /* MIE and SAB carried no accent because the stock LVGL fonts have no
     * accented glyphs and LVGL silently draws nothing for a missing one. The
     * aos_montserrat_* set covers Latin-1, so these are spelled properly now.
     * Both are still three characters wide on screen - UTF-8 makes the strings
     * one byte longer, not the rendered text. */
    /* N_ marks it for the extractor; the translation happens on return, so
     * every caller of this function -the six faces, the calendar, the world
     * clock- ends up translated without touching a line of them. In a static
     * table aos_tr() cannot be called: it is a function. */
    static const char *const days[] = {
        NC_("dia", "DOM"), NC_("dia", "LUN"), NC_("dia", "MAR"), NC_("dia", "MIÉ"),
        NC_("dia", "JUE"), NC_("dia", "VIE"), NC_("dia", "SÁB") };
    return C_("dia", days[((wday % 7) + 7) % 7]);
}

const char *aos_month_name(int mon)
{
    /* Context and not a bare key: "MAR" is Tuesday AND March, and in English
     * they are TUE and MAR. A single catalogue entry cannot serve both. */
    static const char *const months[] = {
        NC_("mes", "ENE"), NC_("mes", "FEB"), NC_("mes", "MAR"), NC_("mes", "ABR"),
        NC_("mes", "MAY"), NC_("mes", "JUN"), NC_("mes", "JUL"), NC_("mes", "AGO"),
        NC_("mes", "SEP"), NC_("mes", "OCT"), NC_("mes", "NOV"), NC_("mes", "DIC") };
    return C_("mes", months[((mon % 12) + 12) % 12]);
}

void aos_keyboard_style(lv_obj_t *kb, const lv_font_t *font)
{
    lv_obj_set_style_text_font(kb, font ? font : aos_font_body, 0);
    lv_obj_set_style_bg_color(kb, lv_color_hex(0x1C1C1E), 0);
    lv_obj_set_style_bg_opa(kb, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(kb, 0, 0);
    lv_obj_set_style_radius(kb, 0, 0);
    lv_obj_set_style_pad_all(kb, 10, 0);
    lv_obj_set_style_pad_gap(kb, 10, 0);
    lv_obj_set_style_bg_color(kb, lv_color_hex(0x4A4A4E), LV_PART_ITEMS);
    lv_obj_set_style_bg_opa(kb, LV_OPA_COVER, LV_PART_ITEMS);
    lv_obj_set_style_text_color(kb, lv_color_white(), LV_PART_ITEMS);
    lv_obj_set_style_border_width(kb, 0, LV_PART_ITEMS);
    lv_obj_set_style_shadow_width(kb, 0, LV_PART_ITEMS);
    lv_obj_set_style_radius(kb, 12, LV_PART_ITEMS);
    lv_obj_set_style_bg_color(kb, lv_color_hex(0x2C2C2E), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(kb, lv_color_white(), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(kb, lv_color_hex(0x8E8E93), LV_PART_ITEMS | LV_STATE_PRESSED);
}
