#!/usr/bin/env python3
"""
The portal's page into C: every file gzipped (the browser unpacks it, the
firmware carries a third of the bytes) as an array, plus a table the server
looks paths up in.

    tools/gen_web_assets.py out.c web/index.html web/app.js web/app.css

Both builds run it (components/aos_portal/CMakeLists.txt and sim/CMakeLists.txt),
so the page is always the one in the source tree. The gzip header's date is
fixed so the output only changes when a file does.
"""
import gzip
import os
import sys

CTYPES = {".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8",
          ".css": "text/css; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png",
          ".ico": "image/x-icon", ".json": "application/json"}


def main():
    out, files = sys.argv[1], sys.argv[2:]
    lines = ["/* Generated by tools/gen_web_assets.py from components/aos_portal/web. Do not edit. */",
             "#include <stdint.h>", "",
             "typedef struct { const char *path, *ctype; const uint8_t *data; uint32_t len; } aos_web_asset_t;", ""]
    table = []
    for i, f in enumerate(files):
        raw = open(f, "rb").read()
        gz = gzip.compress(raw, compresslevel=9, mtime=0)
        name = "/" + os.path.basename(f)
        ctype = CTYPES.get(os.path.splitext(f)[1], "application/octet-stream")
        body = ",".join(str(b) for b in gz)
        lines.append("static const uint8_t a%d[%d] = {%s};" % (i, len(gz), body))
        table.append('    { "%s", "%s", a%d, %d },' % (name, ctype, i, len(gz)))
    lines += ["", "const aos_web_asset_t aos_web_assets[] = {"] + table + ["};",
              "const int aos_web_asset_count = %d;" % len(files), ""]
    text = "\n".join(lines)
    if not os.path.exists(out) or open(out).read() != text:
        open(out, "w").write(text)


if __name__ == "__main__":
    main()
