#!/usr/bin/env python3
"""
The monospaced font of the terminal and the logs: JetBrains Mono Regular
(SIL Open Font License 1.1), ASCII + Latin-1, at 18 and 22 px.

    tools/gen_mono_font.py   -> components/aos_fonts/aos_mono_{18,22}.c + include/aos_mono.h

The TTF is fetched once into ~/.cache/p4os-fonts.
"""
import os
import re
import subprocess
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URL = "https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono@2.304/fonts/ttf/JetBrainsMono-Regular.ttf"
CACHE = os.path.expanduser("~/.cache/p4os-fonts/JetBrainsMono-Regular.ttf")
SIZES = [18, 22]
RANGE = "0x20-0x7E,0xA0-0xFF,0x2022,0x2026,0x2500-0x257F,0x2580-0x259F"
OUT = os.path.join(REPO, "components", "aos_fonts")


def main():
    if not os.path.exists(CACHE):
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        urllib.request.urlretrieve(URL, CACHE)
    for px in SIZES:
        name = "aos_mono_%d" % px
        path = os.path.join(OUT, name + ".c")
        subprocess.run(["lv_font_conv", "--no-compress", "--no-prefilter", "--bpp", "4", "--size", str(px),
                        "--font", CACHE, "-r", RANGE, "--format", "lvgl", "--lv-font-name", name,
                        "--force-fast-kern-format", "-o", path], check=True)
        src = open(path).read()
        src = re.sub(r'#ifdef LV_LVGL_H_INCLUDE_SIMPLE.*?#endif\n', '#include "lvgl.h"\n', src, count=1, flags=re.S)
        src = src.replace(CACHE, "JetBrainsMono-Regular.ttf 2.304")
        src = src.replace(path, "components/aos_fonts/%s.c" % name)
        open(path, "w").write(src)
        print(" ", name)
    hdr = ["/* Generated by tools/gen_mono_font.py - JetBrains Mono Regular (OFL 1.1). */",
           "#pragma once", '#include "lvgl.h"', ""] + ["LV_FONT_DECLARE(aos_mono_%d);" % p for p in SIZES] + [""]
    open(os.path.join(OUT, "include", "aos_mono.h"), "w").write("\n".join(hdr))


if __name__ == "__main__":
    main()
