#!/usr/bin/env python3
"""
Weak default implementations of every function in aos_hal.h.

    tools/gen_hal_stubs.py      -> components/aos_hal/aos_hal_stubs.c

The HAL contract is inherited whole from AmoledOS (~300 functions) and the
P4 board implements it a block at a time (PLAN.md phase 3). Until a block is
written, its functions answer "not available": false, 0, NULL, or "" for a
string. Each is weak, so the real one in aos_hal_p4.c (or hal_sim.c) wins as
soon as it exists, with no list to keep in sync by hand. Run it again after
changing aos_hal.h.
"""
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(REPO, "components", "aos_hal", "include", "aos_hal.h")
OUT = os.path.join(REPO, "components", "aos_hal", "aos_hal_stubs.c")

TYPE_WORDS = {"int", "char", "short", "long", "unsigned", "signed", "float", "double",
              "bool", "void", "const", "volatile", "struct", "enum", "size_t", "time_t"}


def strip_comments(s):
    s = re.sub(r"/\*.*?\*/", " ", s, flags=re.S)
    return re.sub(r"//[^\n]*", " ", s)


def split_params(p):
    out, depth, cur = [], 0, ""
    for ch in p:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def name_params(params):
    named = []
    for i, p in enumerate(params):
        if p == "void" or p == "...":
            named.append(p)
            continue
        if "(" in p:                      # function pointer: already named
            named.append(p)
            continue
        base = re.sub(r"\[.*\]$", "", p).strip()
        toks = re.findall(r"[A-Za-z_]\w*|\*", base)
        last = toks[-1] if toks else ""
        unnamed = (len([t for t in toks if t != "*"]) <= 1 or last == "*" or last in TYPE_WORDS
                   or last.endswith("_t"))
        if unnamed:
            arr = p[len(base):] if p.endswith("]") else ""
            named.append("%s p%d%s" % (base, i, arr))
        else:
            named.append(p)
    return named


def main():
    src = strip_comments(open(HDR).read())
    # preprocessor lines out (they carry no ';'), and bodies of static inline
    # helpers out, so what is left splits cleanly on ';'
    src = "\n".join(l for l in src.split("\n") if not l.strip().startswith("#"))
    while True:
        m = re.search(r"static\s+inline[^{;]*\{", src)
        if not m:
            break
        depth, i = 1, m.end()
        while depth:
            depth += {"{": 1, "}": -1}.get(src[i], 0)
            i += 1
        src = src[:m.start()] + src[i:]
    decls = []
    for stmt in re.sub(r"\s+", " ", src).split(";"):
        stmt = stmt.strip()
        stmt = re.sub(r"^.*\}\s*", "", stmt)          # after a struct/enum body
        m = re.match(r"^((?:const\s+)?[A-Za-z_][\w]*(?:\s+[A-Za-z_]\w*)*\s*\**)\s*\b(aos_hal_\w+)\s*\((.*)\)$", stmt)
        if m and "typedef" not in m.group(1) and not m.group(1).startswith("static"):
            decls.append((m.group(1), m.group(2), m.group(3)))
    seen, out = set(), []
    for ret, name, params in decls:
        ret = ret.strip()
        if name in seen:
            continue
        seen.add(name)
        plist = name_params(split_params(params.strip()))
        sig = "%s %s(%s)" % (ret, name, ", ".join(plist) if plist else "void")
        if ret == "void":
            body = "{ }"
        elif re.fullmatch(r"(const\s+)?char\s*\*", ret):
            body = '{ return ""; }'
        elif "*" in ret:
            body = "{ return NULL; }"
        else:
            body = "{ %s v; memset(&v, 0, sizeof v); return v; }" % ret
        out.append("__attribute__((weak)) %s\n%s\n" % (sig, body))

    head = """/* Generated by tools/gen_hal_stubs.py from aos_hal.h - do not edit.
 *
 * Weak "not available" defaults for every HAL function. The board's
 * aos_hal_p4.c and the simulator's hal_sim.c override them one by one as
 * each block is written (PLAN.md phase 3). */
#include "aos_hal.h"
#include <string.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wunused-parameter"

"""
    open(OUT, "w").write(head + "\n".join(out))
    print("%d stubs -> %s" % (len(out), os.path.relpath(OUT, REPO)))


if __name__ == "__main__":
    main()
